# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://xingweiwang.github.io
title: Xingwei Wang's personal site
email: pkuwangxw@pku.edu.cn
author: Xingwei Wang
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2020 Xingwei Wang. All Rights Reserved.'
credits: 'Credits: This landing page is forked from  github by <a href="https://github.com/swcool">Shane Weng</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/XingWeiWang
  - title: Weibo
    url: https://weibo.com/6390439767/profile?rightmod=1&wvr=6&mod=personnumber&is_all=1#_rnd1577885079094
  - title: zhihu
    url: https://www.zhihu.com/people/wang-xing-wei-29-36/activities
